frase = str(input('Digite seu nome: ')).strip()
print('seu nome em maiusculo {}'.format(frase.upper()))
print('seu nome em minusculo {}'.format(frase.lower()))
print('seu nome tem {} letras no total'.format(len(frase) - frase.count(' ')))
print('seu nome tem {} letras.'.format(frase.find(' ')))
separa= frase.split()
print('se primeiro nome é {} e ele tem {} letras'.format(separa[0], len(separa [0])))
print(frase.capitalize())
print(frase.title())